"""Add topic_id, branch_id, total_questions, correct_answers to quiz_sessions

Revision ID: aadea788b119
Revises: 30d4a4ffc609
Create Date: 2025-08-10 01:53:08.400567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadea788b119'
down_revision: Union[str, Sequence[str], None] = '30d4a4ffc609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_quiz_sessions_topic_id_topics', 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key('fk_quiz_sessions_branch_id_branches', 'topics', ['topic_id'], ['id'])

         # Modify existing columns to be nullable if they were NOT NULL before
        # Note: If there's existing data, making NOT NULL columns nullable is usually safe.
        # If going from nullable to NOT NULL on existing data, you'd need a default or update.
        # Alembic might generate alter_column for these if it detects a change in nullability.
        # Ensure 'score' and 'ended_at' are handled correctly.
        batch_op.alter_column('subject_id', existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column('score', existing_type=sa.Integer(), nullable=True)
        batch_op.alter_column('ended_at', existing_type=sa.DateTime(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_sessions_branch_id_branches', type_='foreignkey')
        batch_op.drop_constraint('fk_quiz_sessions_topic_id_topics', type_='foreignkey')
        batch_op.drop_column('correct_answers')
        batch_op.drop_column('total_questions')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
