"""Add level field to subjects and topics

Revision ID: d304f7bdcdaa
Revises: aadea788b119
Create Date: 2025-08-16 20:24:00.747051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd304f7bdcdaa'
down_revision: Union[str, Sequence[str], None] = 'aadea788b119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_difficulty', sa.Integer(), nullable=True),
    sa.Column('incorrect_streak', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=True))

    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responses', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_column('responses')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    op.drop_table('user_progress')
    # ### end Alembic commands ###
